server:
  port: 9090

spring:
  application:
    name: service-consumer
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: flowerwine 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://flowerwine:280239ou88@localhost:8761/eureka/, http://flowerwine:280239ou88@localhost:8762/eureka/

tx-lcn:
  client:
    manager-address: localhost:8070

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.example.serviceprovider.entity
