server:
  port: 9004

spring:
  application:
    name: service-provider
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://flowerwine:280239ou88@localhost:8761/eureka/, http://flowerwine:280239ou88@localhost:8762/eureka/

